# Generated by Django 5.2.15 on 2026-07-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('lokacija', models.CharField(max_length=100)),
                ('aktivan', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'qr_terminal',
            },
        ),
        migrations.CreateModel(
            name='Smena',
            fields=[
                ('smena_id', models.AutoField(db_column='smena_id', primary_key=True, serialize=False)),
                ('broj_nedelje', models.IntegerField()),
                ('datum_od', models.DateField()),
                ('datum_do', models.DateField()),
            ],
            options={
                'db_table': 'smena',
            },
        ),
        migrations.CreateModel(
            name='Zaposleni',
            fields=[
                ('zaposleni_id', models.AutoField(db_column='zaposleni_id', primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('datum_rodjenja', models.DateField()),
                ('datum_zaposlenja', models.DateField()),
                ('telefon', models.CharField(max_length=30)),
                ('adresa', models.CharField(max_length=100)),
                ('kor_ime', models.CharField(max_length=50, unique=True)),
                ('mejl', models.CharField(max_length=100, unique=True)),
                ('sifra_hash', models.CharField(max_length=255)),
                ('uloga', models.CharField(choices=[('RADNIK', 'Radnik'), ('MENADZER', 'Menadzer'), ('ADMIN', 'Admin')], default='RADNIK', max_length=10)),
                ('aktivan', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'zaposleni',
            },
        ),
        migrations.CreateModel(
            name='QrToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255)),
                ('vreme_generisanja', models.DateTimeField(auto_now_add=True)),
                ('vreme_isteka', models.DateTimeField()),
                ('aktivan', models.BooleanField(default=True)),
                ('terminal', models.ForeignKey(db_column='terminal_id', on_delete=django.db.models.deletion.CASCADE, related_name='tokeni', to='api.qrterminal')),
            ],
            options={
                'db_table': 'qr_token',
            },
        ),
        migrations.CreateModel(
            name='Zadatak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('rok', models.DateTimeField()),
                ('status', models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TO_DO', max_length=15)),
                ('dodeljeni', models.ManyToManyField(blank=True, db_table='zadatak_zaposleni', related_name='zadaci', to='api.zaposleni')),
                ('kreirao', models.ForeignKey(db_column='kreirao_id', on_delete=django.db.models.deletion.PROTECT, related_name='kreirani_zadaci', to='api.zaposleni')),
            ],
            options={
                'db_table': 'zadatak',
            },
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('clanovi', models.ManyToManyField(blank=True, db_table='tim_zaposleni', related_name='timovi', to='api.zaposleni')),
                ('menadzer', models.ForeignKey(db_column='menadzer_id', on_delete=django.db.models.deletion.PROTECT, related_name='timovi_menadzer', to='api.zaposleni')),
            ],
            options={
                'db_table': 'tim',
            },
        ),
        migrations.CreateModel(
            name='SmenaZaposleni',
            fields=[
                ('pk', models.CompositePrimaryKey('smena', 'zaposleni', 'tip_smene', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tip_smene', models.CharField(choices=[('PRVA', 'Prva'), ('DRUGA', 'Druga'), ('TRECA', 'Treca')], max_length=5)),
                ('smena', models.ForeignKey(db_column='smena_id', on_delete=django.db.models.deletion.CASCADE, to='api.smena')),
                ('zaposleni', models.ForeignKey(db_column='zaposleni_id', on_delete=django.db.models.deletion.CASCADE, to='api.zaposleni')),
            ],
            options={
                'db_table': 'smena_zaposleni',
                'unique_together': {('smena', 'zaposleni', 'tip_smene')},
            },
        ),
        migrations.AddField(
            model_name='smena',
            name='zaposleni',
            field=models.ManyToManyField(blank=True, related_name='smene', through='api.SmenaZaposleni', to='api.zaposleni'),
        ),
        migrations.CreateModel(
            name='Obavestenje',
            fields=[
                ('obavestenje_id', models.AutoField(db_column='obavestenje_id', primary_key=True, serialize=False)),
                ('naslov', models.CharField(max_length=100)),
                ('tekst', models.TextField()),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('aktivno', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.PROTECT, related_name='obavestenja', to='api.zaposleni')),
            ],
            options={
                'db_table': 'obavestenje',
            },
        ),
        migrations.CreateModel(
            name='Molba',
            fields=[
                ('molba_id', models.AutoField(db_column='molba_id', primary_key=True, serialize=False)),
                ('naslov', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('datum_za_koji_se_trazi', models.DateField()),
                ('status', models.CharField(choices=[('NA_CEKANJU', 'Na cekanju'), ('ODOBRENA', 'Odobrena'), ('ODBIJENA', 'Odbijena')], default='NA_CEKANJU', max_length=10)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('datum_resenja', models.DateTimeField(blank=True, null=True)),
                ('resio', models.ForeignKey(blank=True, db_column='resio_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resene_molbe', to='api.zaposleni')),
                ('zaposleni', models.ForeignKey(db_column='zaposleni_id', on_delete=django.db.models.deletion.PROTECT, related_name='molbe', to='api.zaposleni')),
            ],
            options={
                'db_table': 'molba',
            },
        ),
        migrations.CreateModel(
            name='Evidencija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('CHECK_IN', 'Check in'), ('CHECK_OUT', 'Check out')], max_length=10)),
                ('vreme', models.DateTimeField(auto_now_add=True)),
                ('qr_token', models.ForeignKey(db_column='qr_token_id', on_delete=django.db.models.deletion.PROTECT, related_name='evidencije', to='api.qrtoken')),
                ('zaposleni', models.ForeignKey(db_column='zaposleni_id', on_delete=django.db.models.deletion.PROTECT, related_name='evidencije', to='api.zaposleni')),
            ],
            options={
                'db_table': 'evidencija',
            },
        ),
    ]
