# Generated by Django 5.2.15 on 2026-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencija',
            name='id',
        ),
        migrations.RemoveField(
            model_name='qrterminal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='qrtoken',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='id',
        ),
        migrations.RemoveField(
            model_name='zadatak',
            name='id',
        ),
        migrations.AddField(
            model_name='evidencija',
            name='evidencija_id',
            field=models.AutoField(db_column='evidencija_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='qrterminal',
            name='qr_terminal_id',
            field=models.AutoField(db_column='qr_terminal_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='qr_token_id',
            field=models.AutoField(db_column='qr_token_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tim',
            name='tim_id',
            field=models.AutoField(db_column='tim_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='zadatak',
            name='prioritet',
            field=models.CharField(choices=[('NIZAK', 'Nizak'), ('SREDNJI', 'Srednji'), ('VISOK', 'Visok')], default='SREDNJI', max_length=10),
        ),
        migrations.AddField(
            model_name='zadatak',
            name='zadatak_id',
            field=models.AutoField(db_column='zadatak_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrterminal',
            name='lokacija',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
